echo "CONFIG_NET_NS=y"                 >> defconfig
echo "CONFIG_IPVLAN=y"                 >> defconfig
echo "CONFIG_IPVLAN_L3S=y"             >> defconfig
echo "CONFIG_VETH=y"                   >> defconfig
echo "CONFIG_NETFILTER_XT_MATCH_OWNER=y" >> defconfig
echo "CONFIG_NETFILTER_XT_MATCH_CGROUP=y" >> defconfig
echo "CONFIG_CGROUP_NET_CLASSID=y"      >> defconfig
echo "CONFIG_NET_CLS_CGROUP=y"          >> defconfig
echo "CONFIG_NETPRIO_CGROUP=y"          >> defconfig
echo "CONFIG_NET_SCH_INGRESS=y"         >> defconfig
